# Generated by Django 4.1.3 on 2022-12-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id_contractor', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_invoice', models.CharField(max_length=64)),
                ('date_of_issue', models.DateField(null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.category')),
                ('id_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.contractors')),
            ],
        ),
        migrations.CreateModel(
            name='PartialBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
                ('plan_amount_category', models.IntegerField()),
                ('execution_amount_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('id_category', models.ManyToManyField(to='budget_app.category')),
                ('nr_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id_budget', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget_name', models.IntegerField(default=2000)),
                ('plan', models.IntegerField(default=0)),
                ('execution', models.IntegerField(default=0)),
                ('categories_budget', models.ManyToManyField(to='budget_app.partialbudget')),
                ('id_category', models.ManyToManyField(to='budget_app.category')),
            ],
        ),
    ]
